apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthdeploy
  labels:
    app: healthdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  healthdeploy
  template:
    metadata:
      labels:
        app:  healthdeploy
    spec:
      containers:
      - name: healthdeploy
        image: shanth19611356248/medicare-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicareservice
  labels:
    app:  healthdeploy
spec:
  selector:
    app:  healthdeploy
  type: NodePort
  ports:
  - nodePort: 31400
    port: 8086
    targetPort: 8086
