apiVersion: apps/v1
kind: Deployment
metadata:
  name: healdeploy
  labels:
    app: healdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  healdeploy
  template:
    metadata:
      labels:
        app:  healdeploy
    spec:
      containers:
      - name: healdeploy
        image: shanth19611356248/medicare-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicareservice
  labels:
    app:  healdeploy
spec:
  selector:
    app:  healdeploy
  type: NodePort
  ports:
  - nodePort: 314000
    port: 8086
    targetPort: 8086
