apiVersion: apps/v1
kind: Deployment
metadata:
  name: heal_deploy
  labels:
    app: heal_deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  heal_deploy
  template:
    metadata:
      labels:
        app:  heal_deploy
    spec:
      containers:
      - name: heal_deploy
        image: shanth19611356248/medicare_app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicare_service
  labels:
    app:  bank_deploy
spec:
  selector:
    app:  bank_deploy
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
